import { useEffect, useMemo, useState } from "react";
import { Activity, BatteryCharging, CheckCircle2, CloudSun, Cpu, FlaskConical, Gauge, Grid3X3, History, HousePlug, Play, RefreshCw, RotateCcw, Siren, Sun, TimerReset, TriangleAlert, Zap } from "lucide-react";
import "./digital-twin-lab.css";

const apiBase=import.meta.env.VITE_API_URL||"/api";
async function api(path:string,token:string,options:RequestInit={}){const response=await fetch(`${apiBase}${path}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...options.headers}});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).detail||`Errore ${response.status}`);return response.json()}
const fmt=(value:any,digits=1)=>value==null?"—":Number(value).toLocaleString("it-IT",{maximumFractionDigits:digits});

export function DigitalTwinLab({token}:{token:string}){
  const [status,setStatus]=useState<any>(null),[runs,setRuns]=useState<any[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(""),[stress,setStress]=useState({units:100,cycles:2,mode:"shared_gateway",max_connections:8}),[stressResult,setStressResult]=useState<any>(null),[qualification,setQualification]=useState<any>(null),[faultValues,setFaultValues]=useState<Record<string,any>>({offline_units:"2",counter_reset_units:"1",latency_ms:250});
  async function load(){try{const [current,history]=await Promise.all([api("/digital-twin/status",token),api("/digital-twin/runs",token)]);setStatus(current);setRuns(history);setError("")}catch(e:any){setError(e.message)}}
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer)},[token]);
  async function action(name:string,fn:()=>Promise<any>){setBusy(name);setError("");try{const result=await fn();if(name==="stress")setStressResult(result.result);if(name==="qualification")setQualification(result.result);await load()}catch(e:any){setError(e.message)}finally{setBusy("")}}
  const snapshot=status?.snapshot||{},faults=status?.faults||{};
  const flow=useMemo(()=>[{id:"pv",label:"Fotovoltaico",value:snapshot.pv_kw,unit:"kW",icon:Sun,tone:"solar"},{id:"storage",label:"Accumulo",value:snapshot.storage_kw,unit:"kW",icon:BatteryCharging,tone:"storage"},{id:"grid",label:"Rete",value:snapshot.grid_kw,unit:"kW",icon:Grid3X3,tone:"grid"},{id:"load",label:"Consumi",value:snapshot.site_load_kw,unit:"kW",icon:HousePlug,tone:"load"},{id:"ev",label:"Ricarica EV",value:snapshot.ev_kw,unit:"kW",icon:Zap,tone:"ev"}], [snapshot]);
  if(!status&&!error)return <div className="twin-loading"><span/><b>Avvio del laboratorio virtuale</b><small>Sincronizzazione dei cinque simulatori…</small></div>;
  return <div className="twin-lab">
    <header className="twin-hero"><div><p>DIGITAL TWIN · PRE-COMMISSIONING</p><h1>Un impianto intero, senza hardware.</h1><span>Scenario coerente, tempo accelerato, fault injection e prove fino a 150 slave Modbus.</span></div><div className={`twin-orbit ${status?.healthy?"online":"offline"}`}><FlaskConical/><i/><b>{status?.healthy?"LAB ONLINE":"LAB PARZIALE"}</b><small>{status?.reachable||0}/{status?.total||0} motori</small></div></header>
    {error&&<div className="twin-error"><TriangleAlert/>{error}<button onClick={()=>void load()}><RefreshCw/>Riprova</button></div>}
    <section className="twin-toolbar"><div><span className="pulse"/><b>{status?.scenario||"Nessuno scenario"}</b><small>{status?.virtual_time?new Date(status.virtual_time).toLocaleString("it-IT"):"—"} · {fmt(status?.time_scale,0)}×</small></div><div><span>Errore bilancio <b>{fmt(status?.balance_error_kw,4)} kW</b></span><button onClick={()=>void load()}><RefreshCw/>Aggiorna</button><button onClick={()=>action("reset",()=>api("/digital-twin/reset",token,{method:"POST",body:"{}"}))}><RotateCcw/>Reset lab</button></div></section>
    <section className="twin-flow"><header><div><p>BILANCIO ISTANTANEO</p><h2>Ecosistema energetico coerente</h2></div><span>I flussi condividono lo stesso orologio e modello fisico.</span></header><div className="flow-canvas"><svg viewBox="0 0 1000 260" preserveAspectRatio="none"><path d="M145 55 C310 55 325 130 500 130"/><path d="M145 205 C310 205 325 130 500 130"/><path d="M855 55 C690 55 675 130 500 130"/><path d="M855 205 C690 205 675 130 500 130"/></svg>{flow.slice(0,4).map((item,index)=><article key={item.id} className={`${item.tone} node-${index}`}><item.icon/><span>{item.label}<b>{fmt(item.value)} <small>{item.unit}</small></b></span><i/></article>)}<div className="flow-core"><Activity/><small>DOMANDA TOTALE</small><b>{fmt(snapshot.site_load_kw)} kW</b><em>Δ {fmt(snapshot.balance_error_kw,4)} kW</em></div><div className="ev-chip"><Zap/><span>EV <b>{fmt(snapshot.ev_kw)} kW</b></span></div></div></section>
    <div className="twin-columns"><main>
      <section className="twin-panel scenarios"><header><div><p>SCENARI RIPRODUCIBILI</p><h2>Scegli il comportamento dell’impianto</h2></div><CloudSun/></header><div>{status?.scenarios?.map((item:any)=><button key={item.id} className={status.scenario===item.id?"active":""} disabled={!!busy} onClick={()=>action(`scenario-${item.id}`,()=>api("/digital-twin/scenario",token,{method:"POST",body:JSON.stringify({scenario:item.id,time_scale:60})}))}><i className={item.tone}/><span><b>{item.name}</b><small>{item.description}</small></span>{status.scenario===item.id?<CheckCircle2/>:<Play/>}</button>)}</div></section>
      <section className="twin-panel faults"><header><div><p>FAULT INJECTION</p><h2>Guasti controllati e reversibili</h2></div><Siren/></header><div className="fault-grid">{status?.fault_catalog?.map((fault:any)=>{const active=faults[fault.id]!==undefined;return <article className={active?"active":""} key={fault.id}><div><Siren/><span><b>{fault.name}</b><small>{fault.description}</small></span></div>{fault.value_kind!=="boolean"&&<input value={faultValues[fault.id]??""} onChange={e=>setFaultValues({...faultValues,[fault.id]:e.target.value})} placeholder={fault.value_kind==="units"?"Unit ID: 1,2":"millisecondi"}/>}<button disabled={!!busy} onClick={()=>{let value:any=true;const raw=faultValues[fault.id];if(fault.value_kind==="units")value=String(raw||"").split(",").map(Number).filter(Boolean);if(fault.value_kind==="milliseconds")value=Number(raw||0);void action(`fault-${fault.id}`,()=>api("/digital-twin/fault",token,{method:"POST",body:JSON.stringify({name:fault.id,enabled:!active,value,profiles:["meter","pv","storage","ev","weather"]})}))}}>{active?"Disattiva":"Inietta"}</button></article>})}</div><footer><span>{Object.keys(faults).length} fault attivi</span><button onClick={()=>action("clear",()=>api("/digital-twin/faults/clear",token,{method:"POST",body:"{}"}))}>Ripristina tutti i segnali</button></footer></section>
    </main><aside>
      <section className="twin-panel stress"><header><div><p>MODBUS LOAD TEST</p><h2>Stress 70–150 slave</h2></div><Cpu/></header><label>Slave simulati<input type="number" min="1" max="150" value={stress.units} onChange={e=>setStress({...stress,units:Number(e.target.value)})}/></label><label>Cicli completi<input type="number" min="1" max="10" value={stress.cycles} onChange={e=>setStress({...stress,cycles:Number(e.target.value)})}/></label><label>Topologia<select value={stress.mode} onChange={e=>setStress({...stress,mode:e.target.value})}><option value="shared_gateway">Gateway condiviso · 1 sessione</option><option value="bounded_pool">Pool TCP limitato</option></select></label>{stress.mode==="bounded_pool"&&<label>Connessioni massime<input type="number" min="1" max="32" value={stress.max_connections} onChange={e=>setStress({...stress,max_connections:Number(e.target.value)})}/></label>}<button className="run-test" disabled={!!busy} onClick={()=>action("stress",()=>api("/digital-twin/stress",token,{method:"POST",body:JSON.stringify(stress)}))}><Gauge/>{busy==="stress"?"Test in corso…":"Avvia stress test"}</button>{stressResult&&<div className={`stress-result ${stressResult.passed?"passed":"failed"}`}><b>{stressResult.passed?"TEST SUPERATO":"TEST DA VERIFICARE"}</b><div><span>Successo<strong>{fmt(stressResult.success_percent)}%</strong></span><span>Throughput<strong>{fmt(stressResult.requests_per_second)} req/s</strong></span><span>P95<strong>{fmt(stressResult.latency_ms?.p95)} ms</strong></span><span>Sessioni<strong>{stressResult.connections_opened}</strong></span></div>{stressResult.coherence_warning&&<small>Rilevati registri identici: il dato non è fisicamente credibile.</small>}</div>}</section>
      <section className="twin-panel qualification"><header><div><p>LAB QUALIFICATION</p><h2>Pre-commissioning automatico</h2></div><CheckCircle2/></header><button disabled={!!busy} onClick={()=>action("qualification",()=>api("/digital-twin/qualification",token,{method:"POST",body:"{}"}))}><Play/>{busy==="qualification"?"Verifica…":"Esegui qualifica"}</button>{qualification&&<><div className="qualification-score"><strong>{qualification.score}</strong><small>/100</small></div><ul>{qualification.checks.map((check:any)=><li key={check.id} className={check.passed?"ok":"bad"}>{check.passed?<CheckCircle2/>:<TriangleAlert/>}<span><b>{check.label}</b><small>{check.detail}</small></span></li>)}</ul></>}</section>
      <section className="twin-panel run-history"><header><div><p>TRACCIABILITÀ</p><h2>Ultime prove</h2></div><History/></header>{runs.slice(0,8).map(run=><article key={run.id}><i className={run.status}/><span><b>{run.kind}</b><small>{run.scenario||new Date(run.started_at).toLocaleString("it-IT")}</small></span><em>{run.status}</em></article>)}{!runs.length&&<div className="twin-empty">Nessuna prova registrata</div>}</section>
    </aside></div>
    <footer className="twin-disclaimer"><TimerReset/><span><b>Ambiente di pre-commissioning</b> I risultati qualificano software, flussi e resilienza; non sostituiscono la validazione con hardware e firmware reali.</span></footer>
  </div>
}
